tier1: playWEB, GRACE, Kitsune, NTb, EDITH, TEPES, FENiX, ELiTE, FLUX, BLOOM, NeoNoir,
  SCOPE, RAWR, SYNCOPY, playHD
tier2: SM737, CMRG, d3g, SiGMA, FraMeSToR, EPSiLON, SPARKS, FGT, DON, HiFi, CtrlHD,
  TayTo
tier3: WASTE, XLARGE, LiNG, FiCO, HiDt, ToonsHub, DERMAGiC, TiGER, GeneMige
banned: YTS, YIFY, EVO, PiRaTeS, LAMA
internal: TLF
anime: SubsPlease, Erai-raws, ASW
games: RUNE, KaOs, DODI, FitGirl
megusta: MeGusta
