wl.tl_shows: [From S04, Doctor on the Edge S01, Your Friends and Neighbours S02, Witch
    Hat Atelier, My Royal Nemesis]
wl.az_shows: [Doctor on the Edge S01, My Royal Nemesis S01, Reborn Rookie S01, Fifties
    Professionals, My Royal Nemesis]
wl.tl_movies: [War Machine 2026, Enola Holmes 3 2026]
wl.az_movies: [Enola Holmes 3 2026]
wl.huno_shows: [Your Friends & Neighbors, Witch Hat Atelier, My Royal Nemesis]
wl.huno_movies: [Enola Holmes 3 2026]
wl.ar_shows: [My Royal Nemesis]
wl.ar_movies: [Enola Holmes 3 2026]
wl.fl_shows: []
wl.fl_movies: []
wl.erai_shows: []
wl.erai_movies: []
wl.ipt_shows: []
wl.ipt_movies: []